### ISSUE TITLE
CF : use of 'number_of_observations' 

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#101]
With variables defined such as :

```
        double CNDC(TIME) ;
                CNDC:_FillValue = 999999. ;
                CNDC:ancillary_variables = "CNDC_num_obs CNDC_sd CNDC_min CNDC_max Total_num_obs" ;
                CNDC:cell_methods = "TIME: mean" ;
                CNDC:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH" ;
                CNDC:long_name = "Mean of sea_water_electrical_conductivity values in time bin, after rejection of flagged data" ;
                CNDC:original_name = "Cond(S/m)" ;
                CNDC:standard_name = "sea_water_electrical_conductivity" ;
                CNDC:units = "S m-1" ;
                CNDC:valid_max = 50000. ;
                CNDC:valid_min = 0. ; 
        int CNDC_num_obs(TIME) ;
                CNDC_num_obs:_FillValue = 999999 ;
                CNDC_num_obs:long_name = "Number of observations in time bin included in time bin average" ;
                CNDC_num_obs:standard_name = "sea_water_electrical_conductivity number_of_observations" ;
                CNDC_num_obs:units = "1" ;

```

The CF conventions allows the use of **number_of_observations** in a standard_name attribute.  ( see http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#standard-name-modifiers) . This is the case with the **CNDC_num_obs** variable. However the CF checker wants to check the units of this variable are the one of the main **CNDC** variable, and is not happy with a value equal to **1**

See this file as example :
[IMOS_SRS-OC-LJCO_KOSTUZ_20140109T065615Z_SRC_FV01_WQM-hourly_C-20151216T052130Z.nc.zip](https://github.com/aodn/compliance-checker/files/106079/IMOS_SRS-OC-LJCO_KOSTUZ_20140109T065615Z_SRC_FV01_WQM-hourly_C-20151216T052130Z.nc.zip)

**Comment by mhidas** [comment]
@lbesnard I think you put the wrong file up as an example. It doesn't have any variables with "number_of_observations" in the standard_name (and it passes the CF checker).

**Comment by mhidas** [comment]
Also, for bugs in the CF checker, please report straight to IOOS (https://github.com/ioos/compliance-checker)

**Comment by lbesnard** [comment]
@mhidas my bad, i uploaded the wrong one
[IMOS_SRS-OC-LJCO_KOSTUZ_20140627T034500Z_SRC_FV02_WQM-daily_C-20151216T053354Z.nc.zip](https://github.com/aodn/compliance-checker/files/107587/IMOS_SRS-OC-LJCO_KOSTUZ_20140627T034500Z_SRC_FV02_WQM-daily_C-20151216T053354Z.nc.zip)

**Comment by mhidas** [comment]
This was reported to IOOS (https://github.com/ioos/compliance-checker/issues/193) and has been fixed.
