### ISSUE TITLE
Merge to master

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#104]
Who is responsible for merging IOOS commits back to our fork ? I don't think we're really up to data. For example this commit is missing, and needed:
https://github.com/ioos/compliance-checker/commit/8a6a520a2243959637a80e7162112ea674b7eb5a

**Comment by mhidas** [comment]
Once https://github.com/aodn/backlog/issues/351 is done, we'll be deploying the checker from master. Pulling new changes from IOOS will still need to be done manually, but the current blockers to this will be removed.

**Comment by mhidas** [comment]
The latest code from IOOS is now deployed in prod. Currently we're deploying from the _master_ branch in [our fork](https://github.com/aodn/compliance-checker), so we'll need to manually keep this up to date with IOOS. However, this gives us a chance to catch any changes they might push that break things for us.
