### ISSUE TITLE
Web interface for test of our version of checker

### ISSUE THREAD

**Issue by ggalibert** [aodn/compliance-checker#107]
A bit like this one http://data.ioos.us/compliance/index.html (maybe IOOS would be ok to share the code for this webpage?) but which would reflect our own configuration/version of the checker currently deployed.

**Comment by mhidas** [comment]
Their web checker code is also open-source: https://github.com/ioos/compliance-checker-web

**Comment by mhidas** [comment]
I have moved this to the backlog: https://github.com/aodn/backlog/issues/389
