### ISSUE TITLE
CF:  check_units want unit att for distribution variable (dimensionless)

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#14]
CF chap 3.1
`Units are not required for dimensionless quantities. A variable with no units attribute is assumed to be dimensionless. However, a units attribute specifying a dimensionless unit may optionally be included.`

The different CMAG variables (particle_distribution_correlation_magnitude_from_acoustic_beam) don't have a standard name (which is fine) and don't have a unit attribute since they are dimensionless variables. This complies with CF. However the netcdf-checker fails on these variables

```
    CMAG1                              :3:     0/ 1 :
        present                        :3:     0/ 1 : units attribute required
    CMAG2                              :3:     0/ 1 :
        present                        :3:     0/ 1 : units attribute required
...
```

example with:
/mnt/ebs/wip/ANMN/timeSeriesProfile_po_permission/new_tb/IMOS_ANMN-QLD_AETVZ_20130620T075900Z_ITFTIS_FV01_ITFTIS-1306-Workhorse-ADCP-464.5_END-20140111T055900Z_C-20150515T020357Z.nc

**Comment by ggalibert** [comment]
I'm happy to modify the toolbox so that it uses a dimensionless unit when relevant. This way we can make sure we always have a variable attribute units?

**Comment by lbesnard** [comment]
I have the feeling this has already been fixed actually, so maybe no need to modify the toolbox. @mhidas ?

**Comment by ggalibert** [comment]
Yeah, it is a CF checker bug. Interesting post here : http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2011/054296.html which quotes CF :

> Units are not required for dimensionless quantities. A variable with no units attribute is assumed to be dimensionless. However, a units attribute specifying a dimensionless unit may optionally be included. The Udunits package defines a few dimensionless units, such as percent, but is lacking commonly used units such as ppm (parts per million). This convention does not support the addition of new dimensionless units that are not udunits compatible. The conforming unit for quantities that represent fractions, or parts of a whole, is "1". The conforming unit for parts per million is "1e-6". Descriptive information about dimensionless quantities, such as sea-ice concentration, cloud fraction, probability, etc., should be given in the long_name or standard_name attributes (see below) rather than the units.

In the case of CMAG (a correlation coefficient between -1 and 1), it is best not to document any units attribute.

**Comment by mhidas** [comment]
@lbesnard @ggalibert This is one of the tricky ones. CF says dimensionless quantities don't need units, but how does the checker code decide whether a variable represents a dimensionless quantity?

For variables with a CF standard_name, we can make use of the canonical unit. If it is "1" the checker can assume it is dimensionless and allow a missing `units` attribute. This is not done at the moment, but could be proposed to IOOS.

If we have no standard_name, then I don't know what the checker can do, other than expect the variable to have `units`. The simplest solution I can think of is to set `units = "1"` for any dimensionless variable.

**Comment by ggalibert** [comment]
My concern @mhidas is that you are going further than the current CF specifications.  Setting `units = "1"` for quantities that are not fractions or parts of a whole is not CF. 

I would think the unit test at this stage is just to check that what is in `units` is udunits compatible.

If you think `units` should always be documented (I do), then we should have a better specification from CF that enables us to use "1" or anything else that would translate into a dimensionless unit.

**Comment by ggalibert** [comment]
I have just modified the toolbox so that any dimensionless parameter that still didn't have any units attribute documented now has one set to 1. https://github.com/aodn/imos-toolbox/commit/b2bd606a9cb55cf420fdb0eba6e4427e031777a9

**Comment by mhidas** [comment]
@ggalibert Thanks. That should fix most of our problems here, at least for Toolbox-produced files. Others will just have to follow suit.

**Comment by ggalibert** [comment]
@mhidas I have improved this according to your comments on the previous commit. See recent commit : https://github.com/aodn/imos-toolbox/commit/edffc5b4d70c4ea22f33c7ab5a922fa1e91a7dbb

**Comment by mhidas** [comment]
@ggalibert Thanks, that looks good.
