### ISSUE TITLE
CF: check_dimension_order ADCP variables

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#16]
All ADCP variables have a wrong order of dimensions in the coordinate attribute.

netcdf-checker ouput

```
dimension_order                        :1:    70/106 : Variable VCUR has a non-
                                                      space-time dimension after
                                                      space-time-dimensions,
...
```

ncdump output

```
  float VCUR(TIME, HEIGHT_ABOVE_SENSOR) ;
                VCUR:coordinates = "TIME LATITUDE LONGITUDE HEIGHT_ABOVE_SENSOR" ;
```

should be instead :

```
 VCUR:coordinates = "HEIGHT_ABOVE_SENSOR TIME LATITUDE LONGITUDE" ;
```

**Comment by mhidas** [comment]
@lbesnard Actually, HEIGHT_ABOVE_SENSOR is a space-time dimension, as it eventually translates to depth, it's just that the checker doesn't recognise it. So it should really be "TIME HEIGHT_ABOVE_SENSOR LATITUDE LONGITUDE" (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#dimensions), but it's a low priority check, so we can probably ignore it for now.

**Comment by ggalibert** [comment]
@mhidas , your link to CF is unrelated to the definition of the variable attribute `coordinates`. In your link CF says :

"we recommend, but do not require [...], those dimensions to appear in the relative order T , then Z , then Y , then X in the CDL definition corresponding to the file..."

Hence `float VCUR(TIME, HEIGHT_ABOVE_SENSOR) ;`

However in chapter 5 http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#coordinate-system :

"The value of the coordinates attribute is a blank separated list of the names of auxiliary coordinate variables . There is no restriction on the order in which the auxiliary coordinate variables appear in the coordinates attribute string."

So we could have `VCUR:coordinates = "TIME LATITUDE LONGITUDE HEIGHT_ABOVE_SENSOR" ;`

**Comment by ggalibert** [comment]
HEIGHT_ABOVE_SENSOR is not considered as a vertical coordinate variable since it doesn't have the attribute "axis" set to Z. NOMINAL_DEPTH already has it. 

The problem with ADCP files is that these are datasets with two kinds of feature types. Some variables like PRES or TEMP are timeSeries while others like VCUR are timeSeriesProfile. So far, CF doesn't support such a special case...

**Comment by mhidas** [comment]
This has been fixed by IOOS. ADCP files created by the latest Toolbox still have the same dimension order, but they don't fail the `dimension_order` check.
