### ISSUE TITLE
Missing IMOS check for Conventions global attribute

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#3]
According to the xls spreadsheet this has been implemented, but looking at the latest commit (f70671855973429f0baa658e98674ceba57b93bd) this doesn't seem to be the case. This is a high priority check.

**Comment by fxmzb123** [comment]
This has been added in branch IMOS-Checker-Issue-3

**Comment by mhidas** [comment]
@fxmzb123 Thanks. Let's merge it in to the main IMOS-Checker branch.

**Comment by fxmzb123** [comment]
I have rebased this branch to imos checker branch.

**Comment by fxmzb123** [comment]
I have resolved the binary file conflict, please merge this with IMOS-Checker branch.

**Comment by fxmzb123** [comment]
@mhidas I have created new branch for this Issue3-check-conventions

**Comment by mhidas** [comment]
This was fixed, but the tidy-up has broken it again. See #30

**Comment by fxmzb123** [comment]
Fixed in #30
