### ISSUE TITLE
CF: all discrete sampling geometry files should have a feature ID variable

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#32]
The CF checker assumes that any file with a **featureType** global attribute is a discrete sampling geometry (DSG) file. For such files, [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#coordinates-metadata) says:

> Where feasible a variable with the attribute **cf_role** should be included.  The only acceptable values of cf_role for Discrete Geometry CF data sets are _timeseries_id_ , _profile_id_ , and _trajectory_id_ .   The variable carrying the cf_role attribute may have any data type.  When a variable is assigned this attribute, it must provide a unique identifier for each feature instance.

The CF checker fails for any file that has a **featureType** global attribute but no variable with a **cf_role** attribute (with the very confusing message 'The cf_role featureType is not properly defined.')

For the moment we only have one feature per file, so a feature id variable is a bit pointless, but if we want them to pass the checker, we'll have to either
- add in a feature id variable; or
- remove the featureType global attribute.

**Comment by ggalibert** [comment]
Is there any way we can feed that back to the people maintaining the CF checker? It seems to me it's a bug from the CF checker. The CF convention is not explicit about this CF checker behaviour and only says "Where feasible...".

**Comment by ggalibert** [comment]
We decided at our last meeting on the netcdf checker that the toolbox will include variables with a **cf_role** attribute.

I suggest such variables are named **TIMESERIES**, **PROFILE** and **TRAJECTORY**.

To add to Marty's quote from CF, I would also mention what just follows:

> CF files that contain timeSeries, profile or trajectory featureTypes, should include only a single occurrence 
> of a cf_role attribute;  CF files that contain timeSeriesProfile or trajectoryProfile may contain two 
> occurrences, corresponding to the two levels of structure in these feature types.

This is relevant for moored ADCP current data which is timeSeriesProfile. They would have a TIMESERIES and a PROFILE variable of length 1 both, with the relevant cf_role attribute.

**Comment by mhidas** [comment]
@ggalibert On that last point, I don't agree. Even if we had more than one timeSeriesProfile feature in a file, we would only require **one** id variable to distinguish them, not two (and, logically, it would have `cf_role = "timeseriesprofile_id"`, but that is not allowed). I don't think that section in the CF document makes sense. 

So for ADCP data, let's just have `TIMESERIES:cf_role = "timeseries_id"`

**Comment by ggalibert** [comment]
Ok, I have made the changes accordingly through the following commits :
https://github.com/aodn/imos-toolbox/commit/19e491d84e8775cd1669aee310b2cb1a08fac0f8
https://github.com/aodn/imos-toolbox/commit/f2b05d70eaba0e0c80d51395c1d0be9a63f92230
https://github.com/aodn/imos-toolbox/commit/741ef2966d49435ba5f5df4393124ad4615dc16b
Files are now successfully passing the CF checker.

**Comment by mhidas** [comment]
Thanks @ggalibert !
