### ISSUE TITLE
CF: DEPTH, coordinates and axes

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#34]
The DEPTH variable computed from pressure is a bit of a tricky case. First we decided it's not a normal data variable and took away its `coordinates` attribute (see #8). Then because of another issue (#12) we decided to not make it an auxiliary coordinate variable either, and then it could have a `coordinates` attribute after all.

I think this latter decision is fine, but will result in this:

```
DEPTH                              :3:     3/ 4 :  
    is_coordinate_var              :3:     0/ 1 : DEPTH is not allowed to
                                                  have an axis attr as it is
                                                  not a coordinate var or
                                                  auxiliary_coordinate_var
```

This is a bit annoying, but according to [CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#coordinates-metadata):

> Only the set of coordinates which are regarded as the nominal (default or preferred) positions should be indicated by the attribute `axis` , which should be assigned string values to indicate the orientations of the axes ( X , Y , Z , or T )

So the solution is simple: the `NOMINAL_DEPTH` variable should have `axis = "Z"`, and `DEPTH` should not.

**Comment by mhidas** [comment]
@ggalibert Not sure if this is already what the toolbox does. Please check.

**Comment by ggalibert** [comment]
`axis = "Z"` will be removed for `DEPTH` in time series.

**Comment by mhidas** [comment]
Thanks @ggalibert
