### ISSUE TITLE
IMOS - check_quality_control_variable_dimensions for BOM files

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#36]
BOM soop netcdf files have a different QC flag type than IMOS.

For example

```
float LONGITUDE(TIME) ;
                LONGITUDE:long_name = "longitude" ;
...
char LONGITUDE_quality_control(TIME, string1) ;
                LONGITUDE_quality_control:standard_name = "longitude status_flag" ;
                LONGITUDE_quality_control:quality_control_conventions = "IMOS Reference Table F" ;
                LONGITUDE_quality_control:quality_control_set = 3 ;
                LONGITUDE_quality_control:quality_control_flag_values = "B, C, D, E, F, G, H, J, K, L, M, Q, S, T, U, V, X, Z" ;
                LONGITUDE_quality_control:quality_control_flag_meanings = "Value_out_of_bounds Time_not_sequential Failed_T_Tw_Td_test Failed_true_wind_recomputation_test Platform_velocity_unrealistic Value_exceeds_threshold Discontinuity Erroneous_value Suspect_value_(visual) Value_located_over_land Instrument_malfunction Pre-flagged_as_suspec
```

As it can be seen in the quality_control_conventions attribute, it's definitely an IMOS one, just different. and it is handled in this function of the imos checker **check_quality_control_conventions_for_quality_control_variable** 

However, the type of this QC variable is different from the type other IMOS QC variables (byte). 
As it can be seen above, the type here is **char** and therefor has to be a function of both TIME and string1 which is equal to 1 so a char value can be written in the netcdf variable.

So of course, this is normal that the variable and it's qc variable have different dimensions. But the imos checker complains. For example, imos checker output:

```
        LW_2_quality_control           :3:     3/ 4 :  
            LW_2                       :3:     1/ 2 :  
                check_dimension        :3:     0/ 1 : Dimension is not same

```

file tested
http://thredds.aodn.org.au/thredds/catalog/IMOS/SOOP/SOOP-ASF/VNAA_Aurora-Australis/meteorological_sst_observations/2013/catalog.html?dataset=IMOS/SOOP/SOOP-ASF/VNAA_Aurora-Australis/meteorological_sst_observations/2013/IMOS_SOOP-ASF_MT_20130315T000000Z_VNAA_FV01_C-20130328T072549Z.nc

**Comment by mhidas** [comment]
@lbesnard I don't really see this as a bug in the checker. The dimensions of a QC variable should be the same as the corresponding data variable, otherwise you can't tell which flag relates to which data value. 

The added string length dimension in these files is unnecessary, since all the flags are single characters. So `char LONGITUDE_quality_control(TIME)` would work just as well, and pass the checker!

The alternative would be to have the checker allow one extra dimension for the QC var, if and only if it is of char type. However I don't think it's a good idea to add work-arounds like this into the checker, and again it shouldn't be necessary because all the QC flag values are single characters.

**Comment by lbesnard** [comment]
> The added string length dimension in these files is unnecessary, since all the flags are single characters. So char LONGITUDE_quality_control(TIME) would work just as well, and pass the checker!

I'm not so sure of this. That would be worth testing/ Always assumed that as soon as you put chars in your variable, you gotta specify the length of it

**Comment by mhidas** [comment]
@lbesnard See e.g. [this file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/profile/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/profile/IMOS_ANMN-NRS_CDEKOSTUZ_20150224T023931Z_NRSROT_FV01_Profile-SBE19plus_C-20150227T052824Z.nc), which has

```
    char DIRECTION ;
            DIRECTION:long_name = "direction_of_the_profile" ;
            DIRECTION:conventions = "A: Ascending profile, D: descending profile" ;
```

Char is a single character.

**Comment by bpasquer** [comment]
Sorry to comment on this a year later but,this is the last point need to comment on for the SOOP-SST compliance, and i am wondering what approach is the best to adopt here. Looking at what unidata says about Character string in the classic model  " a character string must be treated as an array of characters, and array access must be used to read and write character strings as variable data in netCDF datasets.....you must explicitly specify the length of strings to be read from and written to netCDF variables. ".
http://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-c/Classic-Strings.html#Classic-Strings
Looks like the correct approach is to define the length of the string... Now, like you said @mhidas i agree  that in the specific case of single character, the result is the same, i.e. it doesn't really matter but do we want to enforce conventions that are in contradiction to the NetCDF recommendations?

**Comment by mhidas** [comment]
@bpasquer I don't see any contradiction there. That NetCDF document is about _character strings_, which are generally longer than one character.  We're not enforcing anything about character strings. 

What we are enforcing is that quality control variables should have the same dimensions as the corresponding data variable. This can and should be the case even if the qc variable is represented by a single character.

If for some reason we had a need for multi-character qc flags, that would be a different story, but I don't think we do.

**Comment by mhidas** [comment]
@lbesnard @bpasquer Can we close this issue? I still believe this is not something we need to change in the checker, but if there are files that still have this problem we need to track this issue elsewhere. We are going to remove issue tracking from this repo.

**Comment by bpasquer** [comment]
yes you can close the issue. I've followed you recommendations and the files pass the checker .
