### ISSUE TITLE
Attribute not found error in check_quality_control_conventions_for_quality_control_variable

### ISSUE THREAD

**Issue by fxmzb123** [aodn/compliance-checker#45]
Test File:
http://thredds.aodn.org.au/thredds/catalog/IMOS/SOOP/SOOP-TRV/VMQ9273_Solander/By_Cruise/Cruise_START-20150105T073551Z_END-20150106T024945Z/salinity/catalog.html?dataset=IMOS/SOOP/SOOP-TRV/VMQ9273_Solander/By_Cruise/Cruise_START-20150105T073551Z_END-20150106T024945Z/salinity/IMOS_SOOP-TRV_S_20150105T073551Z_VMQ9273_FV01_END-20150106T024945Z_C-20150106T190156Z.nc

**Comment by fxmzb123** [comment]
fixed and see pull request #46

**Comment by mhidas** [comment]
Fixed via #46
