### ISSUE TITLE
IMOS check for QC variable name not implemented

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#50]
The IMOS conventions v1.3 says that the name of a quality control variable must be `<DATA>_quality_control` where  `<DATA>` is the name of the corresponding data variable. This is currently not being checked.

**Comment by mhidas** [comment]
In addition, this is what defines the link between a data variable and its QC variable. Several of the other checks on QC variables should rely on this link. Currently these checks allow the required condition to be met by any data variable.

**Comment by mhidas** [comment]
Another point... for v1.3, not only _data_ variables can have their own QC variable. _Coordinate_ and _auxiliary coordinate_ vars can too.

**Comment by ggalibert** [comment]
An ancillary variable is not necessarily a QC variable. We need to establish a rule that enables us to identify a QC variable. Only then we would be able to check that its name is `<DATA>_quality_control` with `<DATA>` the variable that lists it in its ancillary_variables attribute.

Do you already have an idea on how to identify a QC variable @mhidas ? We could look for variables that include the `quality_control_conventions` attribute which is mandatory for QC variables according to the IMOS NetCDF Conventions document.

**Comment by mhidas** [comment]
@ggalibert Have a look at https://github.com/mhidas/imos-netcdf-conventions/blob/master/IMOS_netCDF_checker_tests_for_manual_v1.3.xls (which we could move into this repo I guess) for the definition of each check. 

I suggest we identify a QC variable as as any variable that
1. has a name that ends in “_quality_control”; **OR**
2. standard_name ends in "status_flag"; **OR**
3. long_name contains "status_flag" or "quality flag"; **OR**
4. has a _flag_values_, or _flag_meanings_ attribute; **OR**
5. has a _quality_control_conventions_ attribute.

These are all mandatory, but the whole point is to identify the variable even if some of them are not there, so that we can report what's missing. If 1. or 2. are true (and maybe 3.), we can also use this to identify the corresponding DATA variable.

**Comment by ggalibert** [comment]
This PR addresses the issue https://github.com/aodn/compliance-checker/pull/81

**Comment by mhidas** [comment]
Fixed in #81
