### ISSUE TITLE
CF: invalid units for sea_surface_wave_directional_variance_spectral_density

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#54]
The new ADCP wave files ([example](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/wave/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/wave/IMOS_ANMN-NRS_WZ_20140601T095900Z_NRSYON_FV01_NRSYON-1406-Workhorse-ADCP-29_END-20141028T025900Z_C-20150722T055015Z.nc)) have this variable:

```
    float SSWV(TIME, FREQUENCY, DIR) ;
            SSWV:standard_name = "sea_surface_wave_directional_variance_spectral_density" ;
            SSWV:units = "m2 s deg-1" ;
```

The CF checker says:

```
SSWV                               :3:     0/ 2 :  
    known                          :3:     0/ 1 : unknown units type (m2 s
                                                  deg-1)
    standard_name                  :3:     0/ 1 : units are m2 s deg-1,
                                                  standard_name units should
                                                  be m2 s rad-1
```

The problem is UDUNITS doesn't recognise "deg".
Solution: change the units of SSWV to "m2 s degree-1" (which it does recognise as being convertible to the CF canonical units).

**Comment by mhidas** [comment]
@ggalibert Another one for the Toolbox.

**Comment by ggalibert** [comment]
Done : https://github.com/aodn/imos-toolbox/commit/15a9dd9c033543fe133e2d1e11cab7a8ce17a12e

**Comment by mhidas** [comment]
Great!
