### ISSUE TITLE
IMOS check for time_coverage_min/max not implemented

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#59]
We should be check that these global attributes match the temporal extent of the data!

**Comment by mhidas** [comment]
Note, this check is implemented in the ACDD suite, but we're not currently planning on running that, so we'll need to do it in the IMOS suite as well.

**Comment by ggalibert** [comment]
I might just copy/paste the ACDD test check_time_extents in https://github.com/ioos/compliance-checker/blob/master/compliance_checker/acdd.py then.

**Comment by mhidas** [comment]
@ggalibert You could try that, though it might be simpler to make use of Ming's `check_value` function in imos/util.py, which has options `OPERATOR_MIN` and `OPERATOR_MAX`. See how these are used to check geospatial_lat_min/max etc...

You'd just need to convert the time_coverage_min/max strings into numbers comparable to the TIME variable values. This can easily be done using the `date2num` method in `cf_units` package.

**Comment by ggalibert** [comment]
@mhidas I've created a PR https://github.com/aodn/compliance-checker/pull/71 to address this.

**Comment by mhidas** [comment]
Fixed in #71
