### ISSUE TITLE
IMOS: check_acknowledgment  - string mismatch

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#6]
acknowledgement attribute is different in ANMN file from the netcdf-checker

example
ncdump output

```
:acknowledgement = "Any users of IMOS data are required to clearly acknowledge the source of the material in the format: \"Data was sourced from the Integrated Marine Observing System (IMOS) - IMOS is supported by the Australian Government through the National Collaborative Research Infrastructure Strategy and the Super Science Initiative.\" If relevant, also credit other organisations involved in collection of this particular datastream (as listed in \'credit\' in the metadata record)."
```

(missing SSI)

check_acknowledgement(self, ds) function definition

```
value = "Data was sourced from the Integrated Marine Observing System (IMOS) - IMOS is supported by the Australian Government through the National Collaborative Research Infrastructure Strategy (NCRIS) and the Super Science Initiative (SSI)"
```

see /mnt/ebs/wip/ANMN/timeSeries/new_tb/IMOS_ANMN-WA_TZ_20140925T080000Z_WATR50_FV01_WATR50-1409-TR-1060-496_END-20150522T023000Z_C-20150522T092647Z.nc

**Comment by atkinsn** [comment]
Note @lbesnard, we have actually updated this acknowledgement statement within all metadata records and websites etc. So if this is something to be added to the checker, it should read as follows:
Any users of IMOS data are required to clearly acknowledge the source of the material derived from IMOS in the format: "Data was sourced from the Integrated Marine Observing System (IMOS) - IMOS is a national collaborative research infrastructure, supported by the Australian Government." If relevant, also credit other organisations involved in collection of this particular datastream (as listed in 'credit' in the metadata record).

**Comment by mhidas** [comment]
I think there are two issues here. 

**1)** The required acknowledgement string has changed over time. We can put this new required acknowledgement string into the next version of the IMOS NetCDF Manual, and require this in the checker for all new files. 
However, all the older files will have older versions of the required string. So if we want to be consistent, we either update all existing files to the new string, or the checker will need to allow or multiple versions.

**2)** Is it worth insisting in the checker that the string be matched exactly, down to the last hyphen or full stop? It's easiest to say it should be exact, but it means there will be many more files to fix! The alternative is to come up with a more complex regular expression the string has to match, allowing a bit more flexibility.

**Comment by mhidas** [comment]
@smancini Any thoughts on this issue?

@ggalibert This will also need to be changed in the Toolbox. See Nat's comment.

**Comment by ggalibert** [comment]
fixed in the toolbox : https://github.com/aodn/imos-toolbox/commit/34194b046fa01135c7660acfa891203d984dd4e1

**Comment by fxmzb123** [comment]
@lbesnard and @mhidas , I have created a branch and pull request for fixing this.

**Comment by mhidas** [comment]
We decided at a meeting today that we would modify the checker so it accepts both the old and new versions of the acknowledgements string (to match as a sub-string of the attribute value, allowing for additional text to be present).
