### ISSUE TITLE
IMOS  check_geospatial_vertical_min_max checks to wrong attributes

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#60]
Looking at the code, the method `check_geospatial_vertical_min_max` seems to apply checks to the attributes `geospatial_lat_min` and `geospatial_lat_max`. Probably a copy-paste that didn't get properly updated.

**Comment by ggalibert** [comment]
Please see PR https://github.com/aodn/compliance-checker/pull/67

**Comment by mhidas** [comment]
Fixed via #67
