### ISSUE TITLE
IMOS filename check for start time always fails

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#74]
So far every file I've tried the filename checker on includes this result:

```
check_file_name_field4             :3:     0/ 1 : File name field4 doesn't
                                                  match time_coverage_start
                                                  attribute
```

At least in some of these cases this is not true.

**Comment by ggalibert** [comment]
This is because the time format in the global attribute is `2015-10-05T01:10:00Z` while it is `20151005T011000Z` in the file name.

**Comment by ggalibert** [comment]
See PR https://github.com/aodn/compliance-checker/pull/83
