### ISSUE TITLE
IMOS quality_control_convention for quality_control_set = 4 not recognized

### ISSUE THREAD

**Issue by bpasquer** [aodn/compliance-checker#77]
File containing the quality_control_set  4 "WOCE quality control procedure (Multidisciplinary Underway Network – CO 2 measurements)" fail to pass the check although the string is written in the exact same manner.
Note that the space in 'CO2' should be removed.

**Comment by mhidas** [comment]
@bpasquer Ok, PR #80 should fix this. To make it easier, it will only check the beginning of the string, up to "WOCE quality control procedure"

**Comment by bpasquer** [comment]
easy , sounds good to me . Thx @mhidas
