### ISSUE TITLE
CF: check_two_dimensional - DEPTH:coordinates references itself

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#8]
ncdump output ;

```
    float DEPTH(TIME) ;
        DEPTH:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH DEPTH" ;

```

netcdf-checker CF test ouput :

```
var                                    :3:    58/68 :  
    DEPTH                              :3:     4/ 5 :  
        coordinates_reference_itself   :3:     0/ 1 : Variable DEPTH's
                                                      coordinate references
                                                      itself

```

For example:
 /mnt/ebs/wip/ANMN/timeSeries/new_tb/IMOS_ANMN-NRS_CKOSTUZ_20120825T054709Z_NRSDAR_FV01_NRSDAR-1208-Surface-WQM-1_END-20121209T014808Z_C-20150324T034821Z.nc

The DEPTH coordinate attribute references to the DEPTH variable, making the cf check fail. Could be an issue to solve in the IMOS TOOLBOX @ggalibert  ?

**Comment by ggalibert** [comment]
Agreed. Now which action to take?

1- In my working copy of the toolbox DEPTH doesn't have any variable attribute `coordinates` anymore. Would that be OK?

2- should we have : `DEPTH:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH" ;` ?

**Comment by mhidas** [comment]
I think the first option is fine. DEPTH is not really a data variable in this case, so doesn't need that attribute.
