### ISSUE TITLE
IMOS - Looking for *_QC files is too broad

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#84]
The IMOS checker currently assumes that a QC variable is defined by having these 2 attributes :

```
flag_values
flag_meanings
```

However some FV02 NetCDF files (from BOM ASF) have some FLAG variables in order to define for example, if a data point comes from one instrument or another instrument (front or back of the ship).

As they already contain the 2 attributes flag_values and meanings, the IMOS checker think they are QC files, leading to some errors

**Comment by mhidas** [comment]
@lbesnard could you please post a link to a sample file and/or list the attributes of these FLAG variables. Also add the incorrect fail messages you get from the checker. Thanks.

**Comment by lbesnard** [comment]
sure, here is the file 
https://www.dropbox.com/s/jkhmsml25gyfalb/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc.20151009-110354?dl=0

**Comment by bpasquer** [comment]
I have come across the same problem with a SOOP_CO2 parameter  SUBFLAG 

SUBFLAG                            :3:     0/ 3 :
        ends_in_quality_control        :3:     0/ 1 : the qc variable 'SUBFLAG'
                                                      does not end in
                                                      '_quality_control'
        quality_control_conventions    :2:     0/ 1 : Variable SUBFLAG should
                                                      have a quality_control_con
                                                      ventions attribute
        quality_control_set            :2:     0/ 1 : Variable SUBFLAG should
                                                      have a quality_control_set
                                                      attribute

**Comment by mhidas** [comment]
@lbesnard @bpasquer Thanks. Looks like we'll have to take this into account when identifying potential QC variables.

@ggalibert Can you have a look at this?

**Comment by ggalibert** [comment]
Ok so what I can suggest is to remove the following condition to identify a quality control variable :
-this variable has variable attributes 'flag_value' or 'flag_meaning'.

There's one condition that could be added though, it is the presence of the variable attribute 'quality_control_conventions'.

**Comment by ggalibert** [comment]
With the suggested changes mentioned above (see PR https://github.com/aodn/compliance-checker/pull/91) on Laurent's file we get:

```
ggalibert@10-nsp-mel:~/compliance-checker$ ./cchecker.py -t=imos /mnt/opendap/1/IMOS/opendap/eMII/checker_test/SOOP/ASF/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc
Running Compliance Checker on the dataset from: /mnt/opendap/1/IMOS/opendap/eMII/checker_test/SOOP/ASF/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc


--------------------------------------------------------------------------------
                    The dataset scored 458 out of 461 points                    
                             during the imos check                              
--------------------------------------------------------------------------------
                               Scoring Breakdown:                               


                                 High Priority                                  
--------------------------------------------------------------------------------
    Name                            :Priority: Score
globalattr                              :3:    66/67
var                                     :3:   392/394
                        No Medium priority tests present                        
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
                  Reasoning for the failed tests given below:                   


Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
globalattr                             :3:    66/67 :  
    abstract                           :3:     0/ 1 :  
        check_atttribute_type          :3:     0/ 1 : Attribute abstract not
                                                      present
var                                    :3:   392/394 :  
    TIME                               :3:    17/18 :  
        units                          :3:     1/ 2 :  
            check_attribute_value      :2:     0/ 1 : The TIME attribute units
                                                      doesn't match the IMOS
                                                      recommended units 'days
                                                      since 1950-01-01 00:00:00
                                                      UTC'
    data_variable                      :3:    68/69 :  
        AIRT_H                         :3:     1/ 2 :  
            _FillValue                 :3:     0/ 1 : AIRT_H has no _FillValue
                                                      attribute.
```

And we pass the unit tests.

**Comment by mhidas** [comment]
@lbesnard @bpasquer I think this was fixed by Guillaume in #91. Can you confirm?

**Comment by bpasquer** [comment]
@mhidas :+1:

**Comment by mhidas** [comment]
Great! Seems to work ok on Loz's file linked above too.
