### ISSUE TITLE
CF - exception error

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#85]
file location :
https://www.dropbox.com/s/jkhmsml25gyfalb/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc.20151009-110354?dl=0

```
Running Compliance Checker on the dataset from: /tmp/IMOS_SOOP-ASF_FMT_20150205T000200Z_ZMFR_FV02.nc
WARNING: The following exceptions occured during the cf checker (possibly indicate compliance checker issues):
cf.check_two_dimensional: maximum recursion depth exceeded while calling a Python object
cf.check_flags: 'numpy.int8' object is not iterable


--------------------------------------------------------------------------------
                    The dataset scored 290 out of 290 points                    
                              during the cf check                               
--------------------------------------------------------------------------------
All tests passed!

```

**Comment by mhidas** [comment]
@lbesnard Thanks for that. These are special cases the checker doesn't currently handle. We'll have to fix that. At the same time they do point to a couple of issues with the file:
- The `coordinates` attribute of a variable should not list that variable itself (e.g. here you have `LATITUDE:coordinates = "TIME LATITUDE LONGITUDE"`). In fact coordinate variables (i.e. lat/lon) and also flag and other ancillary variables don't need to have this attribute at all. It is only relevant for data variables.
- The `flag_values` attribute is usually a _list_ of values, not just a single value ([CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#flags)). What's the point of having a flag variable if there's only one possible value? If there's only one value used in this file, you could still list other possible values here. If nothing else, maybe you could include a value of 0, meaning "unknown"?

**Comment by lbesnard** [comment]
> The coordinates attribute of a variable should not list that variable itself (e.g. here you have LATITUDE:coordinates = "TIME LATITUDE LONGITUDE"). In fact coordinate variables (i.e. lat/lon) and also flag and other ancillary variables don't need to have this attribute at all. It is only relevant for data variables.

thx for your feebacks, I wont add this coordinate attribute to the following variables then : TIME LATITUDE LONGITUDE *_FLAGS *_QUALITY_CONTROL
I guess I should add DEPTH in this list

> The flag_values attribute is usually a list of values, not just a single value (CF). What's the point of having a flag variable if there's only one possible value? If there's only one value used in this file, you could still list other possible values here. If nothing else, maybe you could include a value of 0, meaning "unknown"?

Added 0 unknown

**Comment by mhidas** [comment]
@lbesnard 

> I wont add this coordinate attribute to the following variables then : TIME LATITUDE LONGITUDE *_FLAGS *_QUALITY_CONTROL
> I guess I should add DEPTH in this list

Yes, that would work. DEPTH is a bit tricky when it's a measured variable (derived from pressure). Probably easiest not to give it a coordinates attribute, though I think in the end @ggalibert decided to add it back in for the Toolbox-produced files (https://github.com/aodn/compliance-checker/issues/12#issuecomment-117904375 ... obviously in that case you'd have to not include DEPTH itself in the value of the attribute)

**Comment by mhidas** [comment]
These exceptions have been fixed on master. Unfortunately there are a some other issues in there that need to be resolved before we can merge that branch back in here.

**Comment by lbesnard** [comment]
:+1:

**Comment by mhidas** [comment]
Just confirmed that the latest checker code correctly identifies the above issues in this file, so we can close this as soon as the new version is deployed.

```
Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
§3.5 Flags and flag attributes         :3:    45/59 : flag_values must be a
                                                      list, 'flag_values'
                                                      attribute for variable
                                                      'WIND_FLAG' does not have
                                                      same type (fv: int8, v:
                                                      int16), flag_values must
                                                      be a list,
  ... etc ...
§5.2 Latitude and longitude coordinates:3:     1/ 3 :  
    LATITUDE                           :3:     0/ 1 :  
        coordinates_reference_itself   :3:     0/ 1 : Variable LATITUDE's
                                                      coordinate references
                                                      itself, Variable
                                                      LONGITUDE's coordinate
                                                      references itself
    LONGITUDE                          :3:     0/ 1 :  
        coordinates_reference_itself   :3:     0/ 1 : Variable LATITUDE's
                                                      coordinate references
                                                      itself, Variable
                                                      LONGITUDE's coordinate
                                                      references itself
```
