### ISSUE TITLE
CF: check_vertical_coordinate - DEPTH -  positive attribute required

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#9]
Missing positive attribute in ANMN file

```
vertical                               :3:     5/ 6 :  
    DEPTH                              :3:     1/ 2 :  
        correct_units                  :3:     0/ 1 : vertical variable needs to
                                                      define positive attribute
```

See http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#vertical-coordinate for ref

Example with file:
/mnt/ebs/wip/ANMN/timeSeries/new_tb/IMOS_ANMN-NRS_CKOSTUZ_20120825T054709Z_NRSDAR_FV01_NRSDAR-1208-Surface-WQM-1_END-20121209T014808Z_C-20150324T034821Z.nc

Something to do with the IMOS TOOLBOX @ggalibert  ?

**Comment by ggalibert** [comment]
Agreed, easy to fix for any toolbox version by adding :

`S, positive                  = down`

in imos-toolbox/NetCDF/template/depth_attributes.txt

Will be the case by default in next version.

**Comment by ggalibert** [comment]
Fixed : https://github.com/aodn/imos-toolbox/commit/3d062f11a5e7813d585a7eeaaa4c80b463bbc18b
