### ISSUE TITLE
BOT_DEPTH is not DEPTH

### ISSUE THREAD

**Issue by ggalibert** [aodn/compliance-checker#98]
On the following [file](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/profile/catalog.html?dataset=eMII/checker_test/ANMN/profile/IMOS_ANMN-SA_BCDEFOSTUZ_20080211T235921Z_SA01_FV01_Profile-SeacatPlus_C-20151027T062119Z.nc) the IMOS check reports:

```
var                                    :3:   336/339 :  
    BOT_DEPTH                          :3:    12/15 :  
        positive                       :3:     0/ 1 :  
            vertical                   :3:     0/ 1 : Variable BOT_DEPTH appears
                                                      to be a vertical
                                                      coordinate, should have
                                                      attribute positive =
                                                      'down'
        reference_datum                :3:     0/ 1 :  
            type                       :3:     0/ 1 : Variable attribute
                                                      BOT_DEPTH:reference_datum
                                                      not present
        standard_name                  :3:     1/ 2 :  
            vertical                   :3:     0/ 1 : Variable BOT_DEPTH appears
                                                      to be a vertical
                                                      coordinate, should have
                                                      attribute standard_name =
                                                      'depth'
```

While the two first complaints are relevant, the last one is not. BOT_DEPTH has it own standard_name set to `sea_floor_depth_below_sea_surface`.

**Comment by mhidas** [comment]
[New file](http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NRS/NRSMAI/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKOSTUZ_20150224T235659Z_NRSMAI_FV01_Profile-SBE-19plus_C-20160530T013313Z.nc.html) showing this issue. 

Given that standard_name, I think positive and reference_datum should not be required either.

**Comment by mhidas** [comment]
@ggalibert We could either
1. Look specifically for a variable `BOT_DEPTH`, exclude it from the above checks but instead check it has `standard_name = "sea_floor_depth_below_sea_surface"`, OR
2. Do the same for any variable with `long_name = "sea_floor_depth_below_sea_surface"`, OR
3. Exempt any variable with `standard_name = "sea_floor_depth_below_sea_surface"` from the above checks.

Thoughts? I think I would prefer 3.

**Comment by ggalibert** [comment]
I agree. Preferred solution would be 3.
