### ISSUE TITLE
dimension monotocity not checked

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#99]
Just realised that some of my soop trv files I get from AIMS have a time variable which is not monotonic.
See for example this file:
[IMOS_SOOP-TRV_B_20080930T002727Z_VNCF_FV01_END-20081002T000000Z_C-20160120T154802Z.nc.no.monotonic.zip](https://github.com/aodn/compliance-checker/files/96999/IMOS_SOOP-TRV_B_20080930T002727Z_VNCF_FV01_END-20081002T000000Z_C-20160120T154802Z.nc.no.monotonic.zip)

doing a `ncdump -t -v TIME`  will show the issue. for example, look for `2012` values. The issue is both CF and IMOS checker don't see that the TIME dimension is not monotonic, which surprises me a bit

**Comment by mhidas** [comment]
@lbesnard good spotting. I just had a quick look, and the IMOS checker method `check_coordinate_variables` is supposed to check that the values are monotonic. In fact it's quite a simple bug. Fix coming soon.

**Comment by lbesnard** [comment]
:+1 thanks @mhidas
